apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-web
  namespace: private-ai-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-web
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-web-pdb
  namespace: private-ai-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-web
