apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: private-ai-app
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-web.yaml
  - deployment-inference-gateway.yaml
  - service-and-route.yaml
  - inferenceservice-amd-vulkan.yaml
  - hpa-and-pdb.yaml
