apiVersion: v1
kind: Service
metadata:
  name: ai-web
  namespace: private-ai-app
spec:
  selector:
    app.kubernetes.io/name: ai-web
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ai-web
  namespace: private-ai-app
spec:
  to:
    kind: Service
    name: ai-web
  port:
    targetPort: http
  tls:
    termination: edge
